Repository AY2021S1-CS2103T-T11-4/tp, pull requests merged in 2020-11, with the labels that each got.

#259 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.High

#260 Update initial message
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
Labels: priority.High

#263 Branch fix constraints
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/budget/Budget.java
  src/main/java/seedu/address/model/budget/Threshold.java
  src/main/java/seedu/address/model/expenditure/Price.java
  src/main/java/seedu/address/ui/InfoBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/statebinder/InfoBoxStateBinder.java
  src/main/java/seedu/address/ui/statebinder/StateBinder.java
  src/main/java/seedu/address/ui/statebinder/StateBinderList.java
  src/main/java/seedu/address/ui/statebinder/TitleStateBinder.java
  src/main/resources/view/InfoBox.fxml
Labels: severity.High

#266 Sort UG Update
  docs/UserGuide.md
Labels: type.Task

#272 Add edit tag feature
  src/main/java/seedu/address/logic/commands/budget/EditExpenditureCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/budgetpageparser/EditExpenditureCommandParser.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.Task

#273 Add UML diagram for CreateBudgetCommand and EditBudgetCommand
  docs/diagrams/commandsPlantUML/CreateBudgetCommand.puml
  docs/diagrams/commandsPlantUML/EditBudgetCommand.puml
  docs/diagrams/commandsPlantUML/HelpCommand.puml
  docs/diagrams/commandsPlantUML/SortBudgetCommand.puml
  docs/diagrams/commandsPlantUML/SortExpenditureCommand.puml
  docs/diagrams/commandsPlantUML/diagram/CreateBudgetCommand.png
  docs/diagrams/commandsPlantUML/diagram/EditBudgetCommand.png
  docs/diagrams/commandsPlantUML/diagram/HelpCommand.png
  docs/diagrams/commandsPlantUML/diagram/SortBudgetCommand.png
  docs/diagrams/commandsPlantUML/diagram/SortExpenditureCommand.png
Labels: type.Task

#281 Update List View and fix broken links for DG
  docs/DeveloperGuide.md
Labels: priority.High

#280 Refactor ModelManager to have state interface as attribute
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.High

#282 Rename methods
  src/main/java/seedu/address/model/Nusave.java
  src/main/java/seedu/address/model/budget/Budget.java
  src/main/java/seedu/address/model/budget/BudgetList.java
  src/main/java/seedu/address/model/expenditure/ExpenditureList.java
  src/main/java/seedu/address/model/sort/SortBudgetsByCreateDate.java
  src/main/java/seedu/address/model/sort/SortBudgetsByName.java
  src/main/java/seedu/address/model/sort/SortExpendituresByCreateDate.java
  src/test/java/seedu/address/model/NusaveTest.java
Labels: priority.Medium

#287 Update DG
  docs/DeveloperGuide.md
  docs/SettingUp.md
Labels: priority.High

#288 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteCommandActivityDiagram.png
  docs/diagrams/DeleteCommandActivityDiagram.puml
  docs/diagrams/LogicClassDiagram.png
  docs/diagrams/ModelClassDiagram.png
  docs/diagrams/StateBinders_State_Class_Diagram.png
  docs/diagrams/StateClassDiagram.png
  docs/diagrams/StorageClassDiagram.png
  docs/diagrams/UiClassDiagram.png
  docs/images/DeleteCommandActivityDiagram.png
  src/main/java/seedu/address/state/StateManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
Labels: priority.High

#291 Fix undo and redo
  src/main/java/seedu/address/logic/commands/budget/AddExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/budget/DeleteExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/budget/EditExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/main/ClearBudgetsCommand.java
  src/main/java/seedu/address/logic/commands/main/CreateBudgetCommand.java
  src/main/java/seedu/address/logic/commands/main/DeleteBudgetCommand.java
  src/main/java/seedu/address/logic/commands/main/EditBudgetCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/history/History.java
  src/main/java/seedu/address/model/history/HistoryManager.java
  src/main/java/seedu/address/model/history/Node.java
Labels: priority.High

#301 Added user stories for add expenditure, open and closing budget
  docs/DeveloperGuide.md
Labels: priority.High

#315 Add clear, undo and redo use cases
  docs/DeveloperGuide.md
  docs/team/wenhaogoh.md
Labels: priority.High

#317 Add effort for DG
  docs/DeveloperGuide.md
Labels: priority.High

#325 Add equals method and add test
  src/main/java/seedu/address/logic/commands/main/CreateBudgetCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Nusave.java
  src/main/java/seedu/address/model/expenditure/ExpenditureList.java
  src/main/java/seedu/address/model/history/HistoryManager.java
  src/main/java/seedu/address/model/history/Node.java
  src/main/java/seedu/address/model/history/VersionedNusave.java
  src/main/java/seedu/address/state/StateManager.java
  src/main/java/seedu/address/state/budgetindex/BudgetIndexManager.java
  src/main/java/seedu/address/state/budgetindex/EmptyBudgetIndex.java
  src/test/java/seedu/address/logic/commands/main/CreateBudgetCommandTest.java
  src/test/java/seedu/address/logic/commands/main/HelpBudgetCommandTest.java
Labels: priority.High

#332 Add Budget Test
  docs/team/yu-ming-chen.md
  src/main/java/seedu/address/model/budget/Budget.java
  src/test/java/seedu/address/logic/commands/main/EditBudgetCommandTest.java
  src/test/java/seedu/address/model/budget/BudgetTest.java
  src/test/java/seedu/address/testutil/TypicalBudget.java
Labels: priority.High

#336 Add expenditure test
  src/main/java/seedu/address/model/expenditure/Expenditure.java
  src/test/java/seedu/address/model/budget/BudgetTest.java
  src/test/java/seedu/address/model/expenditure/ExpenditureTest.java
Labels: priority.High

#342 Add CreateBudgetCommandParser Test
  src/main/java/seedu/address/logic/commands/main/CreateBudgetCommand.java
  src/test/java/seedu/address/logic/commands/main/CreateBudgetCommandTest.java
  src/test/java/seedu/address/logic/parser/mainpageparser/CreateBudgetCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalBudget.java
Labels: priority.High

#351 Add sort parser test
  src/main/java/seedu/address/logic/commands/main/SortBudgetCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/budgetpageparser/SortExpenditureCommandParser.java
  src/main/java/seedu/address/logic/parser/mainpageparser/SortBudgetCommandParser.java
  src/test/java/seedu/address/logic/commands/budget/SortExpenditureCommandTest.java
  src/test/java/seedu/address/logic/commands/main/SortBudgetCommandTest.java
  src/test/java/seedu/address/logic/parser/budgetpageparser/SortExpenditureCommandParserTest.java
  src/test/java/seedu/address/logic/parser/mainpageparser/SortBudgetCommandParserTest.java
Labels: priority.High

#371 Fix edit more than 3 tag
  src/main/java/seedu/address/logic/parser/budgetpageparser/EditExpenditureCommandParser.java
Labels: priority.High
