Repository AY2021S1-CS2103T-T11-4/tp, pull requests merged in 2020-10, with the labels that each got.

#29 Update _config.yml
  docs/_config.yml
Labels: documentation

#27 Update README.md
  README.md
Labels: documentation

#30 Branch developer guide
  docs/DeveloperGuide.md
Labels: documentation

#32 Fix README formatting
  README.md
Labels: documentation

#43 Branch add state manager
  docs/AboutUs.md
  docs/images/EkChinHui.png
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/BudgetPageCommand.java
  src/main/java/seedu/address/logic/commands/MainPageCommand.java
  src/main/java/seedu/address/logic/commands/budget/CloseBudgetCommand.java
  src/main/java/seedu/address/logic/commands/main/OpenBudgetCommand.java
  src/main/java/seedu/address/logic/parser/PageParser.java
  src/main/java/seedu/address/logic/parser/budgetpageparser/BudgetPageParser.java
  src/main/java/seedu/address/logic/parser/budgetpageparser/CloseBudgetCommandParser.java
  src/main/java/seedu/address/logic/parser/mainpageparser/MainPageParser.java
  src/main/java/seedu/address/logic/parser/mainpageparser/OpenBudgetCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/budget/Budget.java
  src/main/java/seedu/address/model/expenditure/Expenditure.java
  src/main/java/seedu/address/state/Page.java
  src/main/java/seedu/address/state/State.java
  src/main/java/seedu/address/state/StateManager.java
  src/main/java/seedu/address/state/budgetindex/BudgetIndex.java
  src/main/java/seedu/address/state/budgetindex/BudgetIndexManager.java
  src/main/java/seedu/address/state/budgetindex/EmptyBudgetIndex.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#44 Refactor budget and expenditure to POGO for storage
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Nusave.java
  src/main/java/seedu/address/model/ReadOnlyNusave.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/budget/Budget.java
  src/main/java/seedu/address/model/budget/Title.java
  src/main/java/seedu/address/model/expenditure/Date.java
  src/main/java/seedu/address/model/expenditure/Expenditure.java
  src/main/java/seedu/address/model/expenditure/Name.java
  src/main/java/seedu/address/model/expenditure/Price.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedBudget.java
  src/main/java/seedu/address/storage/JsonAdaptedExpenditure.java
  src/main/java/seedu/address/storage/JsonNusaveStorage.java
  src/main/java/seedu/address/storage/JsonSerializableNusave.java
  src/main/java/seedu/address/storage/NusaveStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High

#47 Add CreateBudgetCommand
  build.gradle
  src/main/java/seedu/address/logic/commands/main/CreateBudgetCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/mainpageparser/CreateBudgetCommandParser.java
  src/main/java/seedu/address/logic/parser/mainpageparser/MainPageParser.java
  src/main/java/seedu/address/model/budget/Budget.java
  src/main/java/seedu/address/model/budget/BudgetName.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedBudget.java
Labels: priority.High, type.Task

#49 Add expenditure command and refactor ui for budgets
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/budget/AddExpenditureCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/budgetpageparser/AddExpenditureCommandParser.java
  src/main/java/seedu/address/logic/parser/budgetpageparser/BudgetPageParser.java
  src/main/java/seedu/address/logic/parser/mainpageparser/OpenBudgetCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Nusave.java
  src/main/java/seedu/address/model/ReadOnlyNusave.java
  src/main/java/seedu/address/model/budget/BudgetList.java
  src/main/java/seedu/address/model/budget/BudgetName.java
  src/main/java/seedu/address/model/budget/exceptions/BudgetNotFoundException.java
  src/main/java/seedu/address/model/expenditure/Expenditure.java
  src/main/java/seedu/address/model/expenditure/ExpenditureName.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedBudget.java
  src/main/java/seedu/address/storage/JsonAdaptedExpenditure.java
  src/main/java/seedu/address/storage/JsonSerializableNusave.java
  src/main/java/seedu/address/ui/BudgetCard.java
  src/main/java/seedu/address/ui/BudgetListPanel.java
  src/main/java/seedu/address/ui/MainPageInfoBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/Title.java
  src/main/resources/view/BudgetListCard.fxml
  src/main/resources/view/BudgetListPanel.fxml
  src/main/resources/view/MainPageInfoBox.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/Title.fxml
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#52 Refactor expenditure and budget attributes
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/budgetpageparser/AddExpenditureCommandParser.java
  src/main/java/seedu/address/logic/parser/mainpageparser/CreateBudgetCommandParser.java
  src/main/java/seedu/address/model/budget/Budget.java
  src/main/java/seedu/address/model/budget/Name.java
  src/main/java/seedu/address/model/expenditure/Date.java
  src/main/java/seedu/address/model/expenditure/Expenditure.java
  src/main/java/seedu/address/model/expenditure/Name.java
  src/main/java/seedu/address/model/expenditure/Price.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedBudget.java
  src/main/java/seedu/address/storage/JsonAdaptedExpenditure.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/ExpenditureCard.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: priority.Low

#64 Add ExitCommand
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/parser/budgetpageparser/BudgetPageParser.java
  src/main/java/seedu/address/logic/parser/mainpageparser/MainPageParser.java
Labels: priority.High

#68 Add Help Command
  src/main/java/seedu/address/logic/parser/budgetpageparser/BudgetPageParser.java
  src/main/java/seedu/address/logic/parser/mainpageparser/MainPageParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High

#69 Ui updates - v1.2
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainPageInfoBox.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/Title.fxml
Labels: priority.High

#73 Add Ui Price On Expenditure Card
  src/main/java/seedu/address/ui/ExpenditureCard.java
  src/main/resources/view/ExpenditureListCard.fxml
Labels: priority.High

#75 Display date and time on the main page
  src/main/java/seedu/address/ui/MainPageInfoBox.java
  src/main/resources/view/MainPageInfoBox.fxml
Labels: priority.High

#77 Branch response messages
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/budget/AddExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/budget/DeleteExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/main/CreateBudgetCommand.java
  src/main/java/seedu/address/logic/commands/main/DeleteBudgetCommand.java
  src/main/java/seedu/address/logic/commands/main/OpenBudgetCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/mainpageparser/MainPageParser.java
Labels: priority.Medium

#78 Update Title on page change
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/budget/CloseBudgetCommand.java
  src/main/java/seedu/address/logic/commands/main/OpenBudgetCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Nusave.java
  src/main/java/seedu/address/model/budget/BudgetList.java
  src/main/java/seedu/address/state/PageTitle.java
  src/main/java/seedu/address/state/State.java
  src/main/java/seedu/address/state/StateManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/Title.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Title.fxml
Labels: priority.High

#86 Change items to cards
  src/main/java/seedu/address/ui/BudgetCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RenderableListPanel.java
  src/main/resources/view/BudgetListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ExpenditureListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RenderableListPanel.fxml
Labels: priority.Medium

#84 Update documentation for commands
  src/main/java/seedu/address/logic/commands/BudgetPageCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/MainPageCommand.java
  src/main/java/seedu/address/logic/commands/budget/AddExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/budget/CloseBudgetCommand.java
  src/main/java/seedu/address/logic/commands/budget/DeleteExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/main/CreateBudgetCommand.java
  src/main/java/seedu/address/logic/commands/main/DeleteBudgetCommand.java
  src/main/java/seedu/address/logic/commands/main/OpenBudgetCommand.java
Labels: priority.High

#87 Display 2 decimal places on ui for whole number prices
  src/main/java/seedu/address/ui/ExpenditureCard.java
Labels: priority.Medium

#89 Display two digits for timer
  src/main/java/seedu/address/ui/MainPageInfoBox.java
Labels: priority.Medium

#91 Branch ui css refactor
  src/main/resources/images/nusave-background.jpg
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainPageInfoBox.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.Medium

#90 Update documentation for parser
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/PageParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/budgetpageparser/AddExpenditureCommandParser.java
  src/main/java/seedu/address/logic/parser/budgetpageparser/BudgetPageParser.java
  src/main/java/seedu/address/logic/parser/budgetpageparser/CloseBudgetCommandParser.java
  src/main/java/seedu/address/logic/parser/budgetpageparser/DeleteExpenditureCommandParser.java
  src/main/java/seedu/address/logic/parser/exceptions/ParseException.java
Labels: priority.High

#99 Branch add font
  src/main/resources/fonts/DoppioOne-Regular.ttf
  src/main/resources/fonts/Lato-Black.ttf
  src/main/resources/fonts/Lato-Bold.ttf
  src/main/resources/fonts/Lato-Light.ttf
  src/main/resources/fonts/Lato-Regular.ttf
  src/main/resources/fonts/Lato-Thin.ttf
  src/main/resources/fonts/Roboto-Black.ttf
  src/main/resources/fonts/Roboto-Bold.ttf
  src/main/resources/fonts/Roboto-Light.ttf
  src/main/resources/fonts/Roboto-Medium.ttf
  src/main/resources/fonts/Roboto-Regular.ttf
  src/main/resources/fonts/Roboto-Thin.ttf
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainPageInfoBox.fxml
  src/main/resources/view/Title.fxml
Labels: priority.Medium

#101 Fix title alignment
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Title.fxml
Labels: priority.Medium

#94 Branch add storage test for v1.2
  src/main/java/seedu/address/storage/JsonAdaptedBudget.java
  src/test/java/seedu/address/storage/JsonAdaptedBudgetTest.java
  src/test/java/seedu/address/storage/JsonAdaptedExpenditureTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTagTest.java
Labels: priority.Medium

#107 Add sample data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Low

#133 Change from del to delete
  src/main/java/seedu/address/logic/commands/budget/DeleteExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/main/DeleteBudgetCommand.java
Labels: priority.Medium

#134 Change date format on ui
  src/main/java/seedu/address/ui/MainPageInfoBox.java
Labels: priority.Medium

#135 Change time format on ui
  src/main/java/seedu/address/ui/MainPageInfoBox.java
Labels: priority.Medium

#139 Add support for 'sort' command for main page parser
  src/main/java/seedu/address/logic/commands/main/SortBudgetCommand.java
  src/main/java/seedu/address/logic/parser/mainpageparser/MainPageParser.java
  src/main/java/seedu/address/logic/parser/mainpageparser/SortBudgetCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Nusave.java
  src/main/java/seedu/address/model/Renderable.java
  src/main/java/seedu/address/model/SortBudgetByName.java
  src/main/java/seedu/address/model/budget/BudgetList.java
Labels: priority.Medium

#142 Branch add date expenditure card
  src/main/java/seedu/address/model/expenditure/Date.java
  src/main/java/seedu/address/model/expenditure/Expenditure.java
  src/main/java/seedu/address/ui/ExpenditureCard.java
  src/main/resources/view/BudgetListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ExpenditureListCard.fxml
  src/main/resources/view/RenderableListPanel.fxml
Labels: priority.High

#144 Reorder filteredList to display latest expenditure at the top (Sort by created on)
  src/main/java/seedu/address/logic/commands/main/SortBudgetCommand.java
  src/main/java/seedu/address/logic/parser/mainpageparser/CreateBudgetCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Nusave.java
  src/main/java/seedu/address/model/SortBudgetByCreateDate.java
  src/main/java/seedu/address/model/budget/Budget.java
  src/main/java/seedu/address/model/budget/BudgetList.java
  src/main/java/seedu/address/model/budget/Date.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedBudget.java
  src/test/java/seedu/address/storage/JsonAdaptedBudgetTest.java
  src/test/java/seedu/address/testutil/BudgetBuilder.java
  src/test/java/seedu/address/testutil/TypicalBudgets.java
Labels: priority.High

#143 Edit 'help' command to display available commands in each page
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/budget/HelpExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/main/HelpBudgetCommand.java
  src/main/java/seedu/address/logic/parser/budgetpageparser/BudgetPageParser.java
  src/main/java/seedu/address/logic/parser/mainpageparser/MainPageParser.java
Labels: priority.High

#141 Add support for 'sort' command for budget page parser
  src/main/java/seedu/address/logic/commands/budget/SortExpenditureCommand.java
  src/main/java/seedu/address/logic/parser/budgetpageparser/BudgetPageParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Nusave.java
  src/main/java/seedu/address/model/SortExpendituresByName.java
Labels: priority.Medium

#149 Debug reset sort upon exit command
  src/main/java/seedu/address/logic/commands/ExitCommand.java
Labels: priority.High

#150 Fix sort by date bug when there is no json file upon first initialization
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
Labels: priority.High

#151 Add support for edit budget command
  src/main/java/seedu/address/logic/commands/main/EditBudgetCommand.java
  src/main/java/seedu/address/logic/parser/mainpageparser/EditBudgetCommandParser.java
  src/main/java/seedu/address/logic/parser/mainpageparser/MainPageParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Nusave.java
  src/main/java/seedu/address/model/budget/BudgetList.java
Labels: priority.High

#153 Add support for edit Expenditure
  src/main/java/seedu/address/logic/commands/budget/EditExpenditureCommand.java
  src/main/java/seedu/address/logic/parser/budgetpageparser/BudgetPageParser.java
  src/main/java/seedu/address/logic/parser/budgetpageparser/EditExpenditureCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Nusave.java
  src/main/java/seedu/address/model/budget/Budget.java
  src/main/java/seedu/address/model/budget/BudgetList.java
Labels: priority.Medium

#158 Fixed edit expenditure to not re-list all items after editing
  src/main/java/seedu/address/logic/commands/budget/EditExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/budget/FindExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/budget/ListExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/main/FindBudgetCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/state/State.java
  src/main/java/seedu/address/state/StateManager.java
  src/test/java/seedu/address/state/StateManager.java
  src/test/java/seedu/address/state/budgetindex/BudgetIndexManager.java
  src/test/java/seedu/address/state/expenditureindex/ExpenditureIndexManager.java
Labels: priority.Medium

#164 Branch error catching
  src/main/java/seedu/address/logic/commands/main/OpenBudgetCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Nusave.java
Labels: severity.Medium

#157 Fix edit error message
  src/main/java/seedu/address/logic/commands/budget/EditExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/main/EditBudgetCommand.java
Labels: priority.High

#166 Fix open command bug
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/budget/CloseBudgetCommand.java
  src/main/java/seedu/address/logic/commands/main/OpenBudgetCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Nusave.java
  src/main/java/seedu/address/model/budget/BudgetList.java
  src/main/java/seedu/address/state/State.java
  src/main/java/seedu/address/state/StateManager.java
Labels: severity.High

#167 Branch refactor
  src/main/java/seedu/address/logic/commands/budget/AddExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/budget/DeleteExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/budget/EditExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/budget/FindExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/budget/HelpExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/budget/ListExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/budget/SortExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/main/CreateBudgetCommand.java
  src/main/java/seedu/address/logic/commands/main/DeleteBudgetCommand.java
  src/main/java/seedu/address/logic/commands/main/EditBudgetCommand.java
  src/main/java/seedu/address/logic/commands/main/FindBudgetCommand.java
  src/main/java/seedu/address/logic/commands/main/HelpBudgetCommand.java
  src/main/java/seedu/address/logic/commands/main/ListBudgetCommand.java
  src/main/java/seedu/address/logic/commands/main/SortBudgetCommand.java
  src/main/java/seedu/address/logic/parser/mainpageparser/FindBudgetCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Nusave.java
Labels: priority.Medium

#170 Refactor assertions
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/budget/DeleteExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/budget/EditExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/budget/FindExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/budget/ListExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/main/DeleteBudgetCommand.java
  src/main/java/seedu/address/logic/commands/main/FindBudgetCommand.java
  src/main/java/seedu/address/logic/commands/main/OpenBudgetCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Nusave.java
  src/main/java/seedu/address/model/budget/Budget.java
  src/main/java/seedu/address/model/budget/BudgetList.java
  src/main/java/seedu/address/state/State.java
  src/main/java/seedu/address/state/StateManager.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.Medium

#174 Fix sort by created on order with latest on top
  src/main/java/seedu/address/model/SortBudgetByCreateDate.java
Labels: priority.High

#175 Add budget and expenditure to top
  src/main/java/seedu/address/model/Nusave.java
  src/main/java/seedu/address/model/budget/Budget.java
  src/main/java/seedu/address/model/budget/BudgetList.java
  src/test/java/seedu/address/storage/JsonAdaptedBudgetTest.java
Labels: priority.High

#180 Update storage component
  docs/DeveloperGuide.md
  docs/images/PojoClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: priority.High, type.Task

#181 Updated create budget command DG
  docs/DeveloperGuide.md
  docs/images/CreateBudgetCommand_sequence_diagram.png
Labels: priority.High, type.Task

#183 Edit delete budget implementation in DG
  docs/DeveloperGuide.md
  docs/images/DeleteBudgetComman_sequence_diagram.png
  docs/images/DeleteSequenceDiagram.png
Labels: priority.High, type.Task

#182 Update user guide
  docs/UserGuide.md
  docs/images/PojoClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: priority.High

#184 Update settings
  build.gradle
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
Labels: priority.High

#186 Enable assertions
  build.gradle
Labels: priority.High

#193 Add support for sort by time and name
  src/main/java/seedu/address/logic/commands/budget/SortExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/main/SortBudgetCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/budgetpageparser/BudgetPageParser.java
  src/main/java/seedu/address/logic/parser/budgetpageparser/SortExpenditureCommandParser.java
  src/main/java/seedu/address/logic/parser/mainpageparser/MainPageParser.java
  src/main/java/seedu/address/logic/parser/mainpageparser/SortBudgetCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Nusave.java
  src/main/java/seedu/address/model/budget/BudgetList.java
  src/main/java/seedu/address/model/expenditure/Date.java
  src/main/java/seedu/address/model/sort/SortBudgetByCreateDate.java
  src/main/java/seedu/address/model/sort/SortBudgetByName.java
  src/main/java/seedu/address/model/sort/SortExpenditureByCreateDate.java
  src/main/java/seedu/address/model/sort/SortExpendituresByName.java
  src/main/java/seedu/address/model/sort/SortType.java
Labels: priority.High

#194 Refactor User Guide and add "Creating a budget" section
  docs/UserGuide.md
  docs/images/CommandScreenShots/6_2_1_1_createBudget.png
Labels: type.Task

#196 Add Sort, Edit command for user guide
  docs/UserGuide.md
  docs/images/CommandScreenShots/6_2_3_1_editBudget.png
  docs/images/CommandScreenShots/6_2_6_1_sortBudget.png
  docs/images/CommandScreenShots/6_3_6_1_sortExpenditure.png
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: type.Task

#197 Add help command for ug and clean up ug
  docs/UserGuide.md
Labels: type.Task

#191 Branch display threshold
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Nusave.java
  src/main/java/seedu/address/model/budget/Budget.java
  src/main/java/seedu/address/model/budget/BudgetList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/state/State.java
  src/main/java/seedu/address/state/StateManager.java
  src/main/java/seedu/address/ui/MainPageInfoBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainPageInfoBox.fxml
Labels: priority.High

#198 Update user guide
  docs/UserGuide.md
Labels: priority.High

#199 Threshold implementation in budget page
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Nusave.java
  src/main/java/seedu/address/model/budget/BudgetList.java
  src/main/java/seedu/address/model/budget/Threshold.java
  src/main/java/seedu/address/storage/JsonAdaptedBudget.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainPageInfoBox.fxml
Labels: priority.High

#201 Update user guide
  docs/UserGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.High

#207 Update user guide introduction
  docs/UserGuide.md
Labels: priority.High

#206 Add Create budget command UML as sample
  docs/DeveloperGuide.md
  docs/diagrams/commandsPlantUML/CreateBudgetCommand.puml
  docs/diagrams/commandsPlantUML/diagram/CreateBudgetCommand.png
Labels: type.Task

#205 Add command summary for UG
  docs/UserGuide.md
Labels: type.Task

#212 Create and add all UG diagrams
  docs/UserGuide.md
  docs/images/CommandScreenShots/5_1_1_1_help.png
  docs/images/CommandScreenShots/5_2_1_1_createBudget.png
  docs/images/CommandScreenShots/5_2_2_1_deleteBudget.png
  docs/images/CommandScreenShots/5_2_3_1_editBudget.png
  docs/images/CommandScreenShots/5_2_4_1_findBudgets.png
  docs/images/CommandScreenShots/5_2_5_1_listBudgets.png
  docs/images/CommandScreenShots/5_2_6_1_sortBudgets.png
  docs/images/CommandScreenShots/5_2_7_1_clearBudgets.png
  docs/images/CommandScreenShots/5_2_8_1_openBudget.png
  docs/images/CommandScreenShots/5_3_1_1_addExpenditure.png
  docs/images/CommandScreenShots/5_3_2_1_deleteExpenditure.png
  docs/images/CommandScreenShots/5_3_3_1_editExpenditure.png
  docs/images/CommandScreenShots/5_3_4_1_findExpenditures.png
  docs/images/CommandScreenShots/5_3_5_1_listExpenditures.png
  docs/images/CommandScreenShots/5_3_6_1_sortExpenditures.png
  docs/images/CommandScreenShots/5_3_7_1_closeBudget.png
  docs/images/CommandScreenShots/6_1_1_openBudget.png
  docs/images/CommandScreenShots/6_1_1_openBudget2.png
  docs/images/CommandScreenShots/6_1_2_closeBudget.png
  docs/images/CommandScreenShots/6_1_2_closeBudget2.png
  docs/images/CommandScreenShots/6_2_1_1_createBudget.png
  docs/images/CommandScreenShots/6_2_3_1_editBudget.png
  docs/images/CommandScreenShots/6_2_4_findBudget.png
  docs/images/CommandScreenShots/6_2_4_findBudget2.png
  docs/images/CommandScreenShots/6_2_6_1_sortBudget.png
  docs/images/CommandScreenShots/6_3_6_1_sortExpenditure.png
  docs/images/GuiLayoutScreenShots/3_1_1_mainPage.png
  docs/images/GuiLayoutScreenShots/3_1_2_budgetCard.png
  docs/images/GuiLayoutScreenShots/3_2_1_budgetPage.png
  docs/images/GuiLayoutScreenShots/3_2_2_expenditureCard.png
  docs/images/QuickStartScreenShots/4_2_terminal.png
Labels: priority.High

#214 Add Test for ModelManager, Nusave, editExpenditureCommand
  src/main/java/seedu/address/logic/commands/budget/EditExpenditureCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Nusave.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditExpenditureCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/NusaveTest.java
  src/test/java/seedu/address/state/StateManager.java
  src/test/java/seedu/address/state/budgetindex/BudgetIndexManager.java
  src/test/java/seedu/address/state/expenditureindex/ExpenditureIndexManager.java
  src/test/java/seedu/address/testutil/EditExpenditureDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalExpenditureIndexes.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.Medium

#219 Add terminal ss
  docs/images/QuickStartScreenShots/4_2_terminal.png
Labels: priority.High

#220 Resize UG screen shot
  docs/images/QuickStartScreenShots/4_2_terminal.png
Labels: priority.High

#216 Add test for budget and expenditure
  src/main/java/seedu/address/model/budget/Budget.java
  src/main/java/seedu/address/model/expenditure/Expenditure.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/budget/BudgetTest.java
  src/test/java/seedu/address/model/expenditure/ExpenditureTest.java
  src/test/java/seedu/address/testutil/BudgetBuilder.java
  src/test/java/seedu/address/testutil/ExpenditureBuilder.java
  src/test/java/seedu/address/testutil/TypicalBudgets.java
  src/test/java/seedu/address/testutil/TypicalExpenditure.java
  src/test/java/seedu/address/testutil/TypicalExpenditures.java
Labels: type.Task
